thermographer-website/config/routes.rb
Thermographer::Application.routes.draw do

  match 'capture' => 'images#capture'
  resources :images

  root :to => "images#capture"

end

thermographer-website/app/models/image.rb
class Image < ActiveRecord::Base
  validates_presence_of :name, :on => :create, :message => "can't be blank"
#  validates_presence_of :author, :on => :create, :message => "can't be blank"
  validates_presence_of :photo, :on => :create, :message => "can't be blank"

  validates_format_of     :name,
                         :with => /[a-zA-Z0-9_-]/,  
                         :message => " must not include spaces and must be alphanumeric, as it'll be used in the URL of your image, like: http://site.org/image/your-image-name. You may use dashes and underscores.",
                         :on => :create
 
 # Paperclip
  has_attached_file :photo,
     :styles => {
     :thumb=> "100x100#",
     :large =>   "400x400>" }

  def image_from_dataurl(data)
    # remove image/png:base,
    data = data.split(',').pop

    # decode base64:
    data = Base64.decode64(data)

    self.photo = Paperclip::string_to_file('capture.png', 'image/png', data)
    self.save
  end

end

thermographer-website/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery

	def mobile?
		(request.env['HTTP_USER_AGENT'].match("Mobi") || params[:format] == "mobile") && params[:format] != "html" && params[:m] != "false" || params[:m] == "true"
	end

end

thermographer-website/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # GET /images
  # GET /images.xml
  def index
    @images = Image.all

    respond_to do |format|
      format.html { render :layout => "mobile" } # index.html.erb
      format.xml  { render :xml => @images }
    end
  end

  def capture
    respond_to do |format|
      format.html { 
        #if mobile?
          render "images/capture.mobile.erb", :layout => "mobile" 
        #else
        #  render 'images/index' 
        #end
      } # show.html.erb
    end
  end

  # GET /images/1
  # GET /images/1.xml
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html { render :layout => "mobile" } # show.html.erb
      format.xml  { render :xml => @image }
    end
  end

  # GET /images/new
  # GET /images/new.xml
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.xml
  def create
    @image = Image.new(params[:image])
    @image.image_from_dataurl(params[:dataurl])

    respond_to do |format|
      if @image.save
        format.html { redirect_to(@image, :notice => 'Image was successfully created.') }
        format.xml  { render :xml => @image, :status => :created, :location => @image }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.xml
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to(@image, :notice => 'Image was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.xml
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to(images_url) }
      format.xml  { head :ok }
    end
  end
end

thermographer-website/app/helpers/application_helper.rb
module ApplicationHelper
end

thermographer-website/app/helpers/images_helper.rb
module ImagesHelper
end

thermographer-website/app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_area :data %>
  </div>
  <div>
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

thermographer-website/app/views/images/capture.mobile.erb
<script src="/javascripts/getUserMedia.js"> </script>
<script src="/javascripts/capture.js"> </script>

<div data-role="page" id="page1" data-theme="a">
  <div data-theme="a" data-role="header">
    <a style="float:right;" data-inline="true" data-ajax="false" data-role="button" data-transition="fade" data-theme="a" href="/images">&laquo; Home</a>
    <h3>
    Thermographer
    </h3>
  </div>
  <div data-role="content" style="padding: 15px;background:#444;" id="content">

    <canvas style="width:100%;height:400px;" id="canvas"></canvas> 
    <canvas style="width:100%;height:400px;display:none;" id="buffer"></canvas> 
    <div style="width:100%;display:none;" id="webcam"></div> 

	<br />
    	<a data-inline="true" data-ajax="false" data-role="button" data-transition="fade" data-theme="a" data-icon="check" href="#page2" onClick="$T.saveImage();">Save</a>
	<a data-inline="true" data-ajax="false" data-role="button" data-transition="fade" data-theme="a" href="javascript:void(0);" onClick="$T.clear()">Clear</a>

<!--
    <div data-role="fieldcontain">
      <fieldset data-role="controlgroup">
        <label for="toggleswitch1">Geotag</label>
        <select name="toggleswitch1" id="geotag-toggle" data-theme="a" data-role="slider" data-mini="true">
           <option value="off">Off</option>
           <option value="on">On</option>
        </select>
      </fieldset>
    </div>

    <% unless false %><p><a data-ajax="false" href="/login">Log in</a> to save your image</p><% end %>
-->
    <p><small>This interface works on mobile phones only on <a href="https://play.google.com/store/apps/details?id=com.opera.browser">Opera Mobile</a>, the only mobile browser currently supporting the MediaStream API. It works on desktop Chrome and Opera.</small></p>
    <p><small>Running slow? <a href="?size=320x240">Try the small version</a>. Or the <a href="?size=1280x720">large version</a></small></p>

    <p><a data-ajax="false" href="https://github.com/jywarren/thermographer">Thermographer is free software</a> by <a data-ajax="false" href="http://publiclaboratory.org">Public Lab</a></p>

  </div>
</div>

<div data-role="page" id="page2">

	<h2>Save this image</h2>

	<!--
	<% if true %>
		<p>You must be <a target="_blank" data-ajax="false" href="/login">logged in</a> to save images.</p>
	<% else %>
		<p>(logged in as <%=h current_user.login %>)</p>
	<% end %>
	-->

	<form action="/images" method="post" id="saveForm" target="_blank" onSubmit="$T.cancelSave();window.location='#page1'">
		<label for="image_name">Title:</label><br />
		<input name="image[name]" id="image_name" type="text" /><br />
		<!--
			<label for="tags">Tags:</label><br />
			<input name="tags" id="image_tags" value="mobile," type="text" /><br />
		-->
		<label for="image_description">Notes:</label>
		<textarea name="image[description]" id="image_description"></textarea><br />
		<input name="dataurl" type="hidden" id="dataurl" />
		<!--
			<input name="geotag" type="hidden" id="geotag" />
			<input name="lat" type="hidden" id="lat" />
			<input name="lon" type="hidden" id="lon" />
		-->
	</form>
	<a data-ajax="false" data-role="button" data-transition="fade" data-theme="a" href="javascript:void(0);" onClick="$('#saveForm').submit()">Save</a>
	<a data-ajax="false" data-role="button" data-transition="fade" data-theme="d" href="#page1" onClick="$T.cancelSave()">&laquo; Back</a>

</div>

<div data-role="page" id="page3">
	<div data-role="fieldcontain">
		<fieldset data-role="controlgroup" data-mini="true">
			<label for="sample_slider">Range</label>
			<input type="range" name="slider" id="sample_slider" value="250" min="0" max="640" data-highlight="false" />
		</fieldset>
	</div>
</div>

<script> (function () { 
	$T.initialize({
		<% if params[:size] %>
		width:<%= params[:size].split('x')[0] %>,
		height:<%= params[:size].split('x')[1] %>,
		<% end %>
		calibrated:false,
		mobile:true
	}) 
	setInterval($T.capture,100)
})() </script>

thermographer-website/app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

thermographer-website/app/views/images/index.html.erb
<div data-role="page" id="page1">

        <div data-theme="d" data-role="header">
                <a data-ajax="false" data-role="button" data-transition="fade" data-theme="c" href="/capture">&laquo; Back to capture</a>
                <h3>
			Thermal images
                </h3>
        </div>

<table>
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Author</th>
    <th>Description</th>
    <!--<th></th>-->
  </tr>

<% @images.each do |image| %>
  <tr>
    <td><a href="/images/<%= image.id %>"><img id="image" style="width:100%" src="<%= image.photo.url(:thumb) %>" /></a></td>
    <td><a href="/images/<%= image.id %>"><%= image.name %></a></td>
    <td><%= image.author %></td>
    <td><%= image.description %></td>
    <!--<td><%= link_to 'Destroy', image, :confirm => 'Are you sure?', :method => :delete %></td>-->
  </tr>
<% end %>
</table>

</div>

thermographer-website/app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

thermographer-website/app/views/images/show.html.erb
<script src="/javascripts/show.js"> </script>

<div data-role="page" id="page1">

        <div data-theme="d" data-role="header">
                <a data-ajax="false" data-role="button" data-transition="fade" data-theme="c" href="/capture">&laquo; Back to capture</a>
                <h3>
                        <%= @image.name %>
                </h3>
        </div>

        <div data-role="content" style="padding: 15px">
                <img id="image" style="width:100%" src="<%= @image.photo.url(:large) %>" />
	</div>
</div>

thermographer-website/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thermographer</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <script>
    $(document).bind("mobileinit", function(){
      // disable ajax nav
      $.mobile.ajaxEnabled = false;
    });
  </script>
</head>
<body>

<%= yield %>

</body>
</html>

thermographer-website/app/views/layouts/mobile.html.erb
<!DOCTYPE html>
<% if params[:action] == "capture" %>
<html manifest="/index.manifest">
<% else %>
<html>
<% end %>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>PLOTS Thermographer</title>
        <link rel="stylesheet" href="/stylesheets/jquery.mobile-1.1.0.min.css" />
	<link rel="stylesheet" href="/stylesheets/smoothness/jquery-ui-1.8.21.custom.css">
        <link rel="stylesheet" href="/stylesheets/mobile.css" />
        <script src="/javascripts/jquery.min.js">
        <script src="/javascripts/todataurl.js">
        </script>
        <script>
          $(document).bind("mobileinit", function(){
            // disable ajax nav
            $.mobile.ajaxEnabled = false;
          });
        </script>
        <script src="/javascripts/jquery.mobile-1.1.0.min.js"></script>
        <script src="/javascripts/application.js"></script>
    </head>
    <body>
    <%= yield %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-34050589-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
    </body>
</html>